"use strict";
// auto-generated by `jswt reexport`
// DO NOT EDIT

module.exports = require("./lib/@dashincubator/blocktx.js")

// these typedef reexports will be available to dependent packages
/**
 * @typedef {import('./blocktx.js').TxPrivateKey} TxPrivateKey
 * @typedef {import('./blocktx.js').TxPublicKey} TxPublicKey
 * @typedef {import('./blocktx.js').TxInput} TxInput
 * @typedef {import('./blocktx.js').TxInputRaw} TxInputRaw
 * @typedef {import('./blocktx.js').TxInputHashable} TxInputHashable
 * @typedef {import('./blocktx.js').TxInputSigned} TxInputSigned
 * @typedef {import('./blocktx.js').TxOutput} TxOutput
 * @typedef {import('./blocktx.js').TxInfo} TxInfo
 * @typedef {import('./blocktx.js').TxInfoSigned} TxInfoSigned
 * @typedef {import('./blocktx.js').TxDeps} TxDeps
 * @typedef {import('./blocktx.js').TxSignOpts} TxSignOpts
 */
