"use strict";
// auto-generated by `jswt reexport`
// DO NOT EDIT

module.exports = require("./lib/dashtx.js")

// these typedef reexports will be available to dependent packages
/**
 * @typedef {import('./bak/dashtx.js').Tx} Tx
 * @typedef {import('./bak/dashtx.js').TxUtils} TxUtils
 * @typedef {import('./bak/dashtx.js').tx} tx
 * @typedef {import('./bak/dashtx.js').TxPrivateKey} TxPrivateKey
 * @typedef {import('./bak/dashtx.js').TxPublicKey} TxPublicKey
 * @typedef {import('./bak/dashtx.js').TxSignature} TxSignature
 * @typedef {import('./bak/dashtx.js').TxDeps} TxDeps
 * @typedef {import('./bak/dashtx.js').TxFees} TxFees
 * @typedef {import('./bak/dashtx.js').TxInfo} TxInfo
 * @typedef {import('./bak/dashtx.js').TxInfoSigned} TxInfoSigned
 * @typedef {import('./bak/dashtx.js').TxInput} TxInput
 * @typedef {import('./bak/dashtx.js').TxInputHashable} TxInputHashable
 * @typedef {import('./bak/dashtx.js').TxInputRaw} TxInputRaw
 * @typedef {import('./bak/dashtx.js').TxInputUnspent} TxInputUnspent
 * @typedef {import('./bak/dashtx.js').TxInputSortable} TxInputSortable
 * @typedef {import('./bak/dashtx.js').TxHasSats} TxHasSats
 * @typedef {import('./bak/dashtx.js').TxInputSigned} TxInputSigned
 * @typedef {import('./bak/dashtx.js').TxOutput} TxOutput
 * @typedef {import('./bak/dashtx.js').TxOutputSortable} TxOutputSortable
 * @typedef {import('./dashtx.js').Tx} Tx
 * @typedef {import('./dashtx.js').TxUtils} TxUtils
 * @typedef {import('./dashtx.js').tx} tx
 * @typedef {import('./dashtx.js').TxPrivateKey} TxPrivateKey
 * @typedef {import('./dashtx.js').TxPublicKey} TxPublicKey
 * @typedef {import('./dashtx.js').TxSignature} TxSignature
 * @typedef {import('./dashtx.js').TxDeps} TxDeps
 * @typedef {import('./dashtx.js').TxFees} TxFees
 * @typedef {import('./dashtx.js').TxInfo} TxInfo
 * @typedef {import('./dashtx.js').TxInfoSigned} TxInfoSigned
 * @typedef {import('./dashtx.js').TxInput} TxInput
 * @typedef {import('./dashtx.js').TxInputHashable} TxInputHashable
 * @typedef {import('./dashtx.js').TxInputRaw} TxInputRaw
 * @typedef {import('./dashtx.js').TxInputUnspent} TxInputUnspent
 * @typedef {import('./dashtx.js').TxInputSortable} TxInputSortable
 * @typedef {import('./dashtx.js').TxHasSats} TxHasSats
 * @typedef {import('./dashtx.js').TxInputSigned} TxInputSigned
 * @typedef {import('./dashtx.js').TxOutput} TxOutput
 * @typedef {import('./dashtx.js').TxOutputSortable} TxOutputSortable
 */
